'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Button } from '@/components/ui/button'
import { Textarea } from '@/components/ui/textarea'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Lightbulb, Sparkles, ArrowRight, Clock, Target, Zap } from 'lucide-react'

const examplePrompts = [
  {
    title: "Student Side Hustle",
    prompt: "I’m a broke college student who wants to start a side hustle with minimal upfront cost",
    category: "Side Hustle"
  },
  {
    title: "Tech SaaS",
    prompt: "Give me a SaaS idea for solo developers that can be built in 3 months",
    category: "SaaS"
  },
  {
    title: "Local Business",
    prompt: "I want a local business with recurring revenue that doesn’t require technical skills",
    category: "Local Business"
  },
  {
    title: "AI-Powered Service",
    prompt: "Help me create a service business that leverages AI to automate client work",
    category: "AI Service"
  },
  {
    title: "E-commerce Niche",
    prompt: "I want to start an e-commerce business targeting a specific niche market",
    category: "E-commerce"
  },
  {
    title: "Content Creator",
    prompt: "Give me ideas for a content business that can generate passive income",
    category: "Content"
  }
]

const features = [
  {
    icon: <Lightbulb className="h-6 w-6 text-yellow-500" />,
    title: "AI-Powered Ideas",
    description: "Get personalized business concepts generated by GPT-4"
  },
  {
    icon: <Target className="h-6 w-6 text-blue-500" />,
    title: "Tailored Results",
    description: "Ideas matched to your skills, budget, and preferences"
  },
  {
    icon: <Clock className="h-6 w-6 text-green-500" />,
    title: "Instant Generation",
    description: "Get actionable business ideas in seconds, not hours"
  },
  {
    icon: <Zap className="h-6 w-6 text-purple-500" />,
    title: "Ready to Execute",
    description: "Complete with monetization strategy and next steps"
  }
]

export default function HomePage() {
  const [prompt, setPrompt] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)
  const router = useRouter()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!prompt.trim() || isGenerating) return

    setIsGenerating(true)
    try {
      const response = await fetch('/api/generate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ prompt }),
      })

      if (!response.ok) {
        throw new Error('Failed to generate idea')
      }

      const data = await response.json()
      
      // Store the result and navigate to results page
      localStorage.setItem('generatedIdea', JSON.stringify({
        prompt,
        idea: data.idea,
        timestamp: new Date().toISOString()
      }))
      
      router.push('/result')
    } catch (error) {
      console.error('Error generating idea:', error)
      alert('Failed to generate business idea. Please try again.')
    } finally {
      setIsGenerating(false)
    }
  }

  const handleExampleClick = (examplePrompt: string) => {
    setPrompt(examplePrompt)
  }

  return (
    <div className="container mx-auto px-4 py-8 max-w-6xl">
      {/* Navigation */}
      <div className="flex justify-between items-center mb-8">
        <div className="flex items-center gap-2">
          <Sparkles className="h-6 w-6 text-blue-600" />
          <span className="font-semibold text-lg">BizPrompt</span>
        </div>
        <Button 
          variant="outline" 
          onClick={() => router.push('/explore')}
        >
          Explore Ideas
        </Button>
      </div>

      {/* Header */}
      <div className="text-center mb-12">
        <div className="flex items-center justify-center gap-2 mb-4">
          <Sparkles className="h-8 w-8 text-blue-600" />
          <h1 className="text-4xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
            BizPrompt
          </h1>
        </div>
        <p className="text-xl text-muted-foreground mb-4">
          Generate personalized business ideas with AI
        </p>
        <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
          From side hustles to SaaS companies, get actionable business concepts tailored to your skills, budget, and goals.
        </p>
      </div>

      {/* Features Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
        {features.map((feature, index) => (
          <Card key={index} className="text-center border-0 shadow-sm">
            <CardContent className="pt-6">
              <div className="flex justify-center mb-3">
                {feature.icon}
              </div>
              <h3 className="font-semibold mb-2">{feature.title}</h3>
              <p className="text-sm text-muted-foreground">{feature.description}</p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Main Prompt Input */}
      <Card className="mb-12 border-2 border-dashed border-muted-foreground/25">
        <CardHeader>
          <CardTitle className="text-center">What kind of business idea are you looking for?</CardTitle>
          <CardDescription className="text-center">
            Describe your situation, goals, or preferences. Be as specific as you’d like.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <Textarea
              placeholder="E.g., I’m a designer looking for a SaaS idea I can build on weekends..."
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              className="min-h-[120px] text-lg"
              maxLength={500}
            />
            <div className="flex items-center justify-between">
              <span className="text-sm text-muted-foreground">
                {prompt.length}/500 characters
              </span>
              <Button 
                type="submit" 
                disabled={!prompt.trim() || isGenerating}
                size="lg"
                className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700"
              >
                {isGenerating ? (
                  <>
                    <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2" />
                    Generating...
                  </>
                ) : (
                  <>
                    Generate Idea
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </>
                )}
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>

      {/* Example Prompts */}
      <div className="mb-12">
        <h2 className="text-2xl font-semibold text-center mb-6">
          Need inspiration? Try these examples
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {examplePrompts.map((example, index) => (
            <Card 
              key={index} 
              className="cursor-pointer hover:shadow-md transition-shadow border-muted-foreground/20"
              onClick={() => handleExampleClick(example.prompt)}
            >
              <CardContent className="p-4">
                <div className="flex items-center justify-between mb-2">
                  <h3 className="font-medium">{example.title}</h3>
                  <Badge variant="secondary" className="text-xs">
                    {example.category}
                  </Badge>
                </div>
                <p className="text-sm text-muted-foreground">{example.prompt}</p>
              </CardContent>
            </Card>
          ))}
        </div>
      </div>

      {/* CTA Section */}
      <Card className="text-center bg-gradient-to-r from-blue-50 to-purple-50 border-0">
        <CardContent className="p-8">
          <h2 className="text-2xl font-semibold mb-4">
            Ready to discover your next business opportunity?
          </h2>
          <p className="text-muted-foreground mb-6 max-w-2xl mx-auto">
            Join thousands of entrepreneurs who have found their perfect business idea with BizPrompt.
            Get started in seconds with our AI-powered generator.
          </p>
          <Button 
            size="lg"
            onClick={() => document.querySelector('textarea')?.focus()}
            className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700"
          >
            Start Generating Ideas
            <Sparkles className="ml-2 h-4 w-4" />
          </Button>
        </CardContent>
      </Card>
    </div>
  )
}
